const GET_SAVED_VIDEOS_START = 'GET_SAVED_VIDEOS_START'
const GET_SAVED_VIDEOS_END = 'GET_SAVED_VIDEOS_END'

const GET_INCIDENCES_LIST_START = 'GET_INCIDENCES_LIST_START'
const GET_INCIDENCES_LIST_END = 'GET_INCIDENCES_LIST_END'

const TOGGLE_VISIBILITY_START = 'TOGGLE_VISIBILITY_START'
const TOGGLE_VISIBILITY_END = 'TOGGLE_VISIBILITY_END'

const CHANGE_SUBSCRIPTION_START = 'CHANGE_SUBSCRIPTION_START'
const CHANGE_SUBSCRIPTION_END = 'CHANGE_SUBSCRIPTION_END'