export const ROLES = ["ROLE_SUPER_ADMINISTRATEUR","ROLE_ADMINISTRATEUR","ROLE_USER","ROLE_SERVICE_TECHNIQUE","ROLE_REVENDEUR","ROLE_INSTALLATEUR","ROLE_INTERVENTION","ROLE_CLIENT_BB"]
export const ROLES1 = ["ROLE_USER","ROLE_SERVICE_TECHNIQUE","ROLE_REVENDEUR","ROLE_INSTALLATEUR","ROLE_INTERVENTION","ROLE_CLIENT_BB","ROLE_CLIENT_BC"]
